name = "my-weather-bot"
main = "src/worker.ts"
compatibility_date = "2026-03-02"

[API]
API_BASE_URL = "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"

[assets]
directory = "./dist"
binding = "ASSETS"
